#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://postgres:5432/produitdb
#    username: postgres
#    password: tall
#    hikari:
#      initialization-fail-timeout: 0
#jpa:
#  database-platform: org.hibernate.dialect.PostgresPlusDialect
#  generate-ddl: true
#  show-sql: true
#  hibernate:
#    ddl-auto: create
#server:
#  port: 8090

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/produitdb?serverTimezone=UTC
    username: postgres
    password: tall
  servlet:
    multipart:
      max-file-size: 10000KB
      max-request-size: 10000KB

server:
  port: 8090
